name: web_app
channels:
  - defaults
dependencies:
  - astroid=2.0.4=py35_0
  - backcall=0.1.0=py35_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py35_1
  - decorator=4.3.0=py35_0
  - ipython=6.5.0=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - isort=4.3.4=py35_0
  - jedi=0.12.1=py35_0
  - lazy-object-proxy=1.3.1=py35h14c3975_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - mccabe=0.6.1=py35_1
  - openssl=1.0.2p=h14c3975_0
  - parso=0.3.1=py35_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pip=10.0.1=py35_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - ptyprocess=0.6.0=py35_0
  - pygments=2.2.0=py35h0f41973_0
  - pylint=2.1.1=py35_0
  - python=3.5.3=1
  - readline=6.2=2
  - setuptools=40.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - six=1.11.0=py35_1
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - traitlets=4.3.2=py35ha522a97_0
  - typed-ast=1.1.0=py35h20cf15d_0
  - wcwidth=0.1.7=py35hcd08066_0
  - wheel=0.31.1=py35_0
  - wrapt=1.10.11=py35h14c3975_2
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - pip:
    - alembic==1.0.3
    - aniso8601==4.0.1
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - click==7.0
    - flask==1.0.2
    - flask-login==0.4.1
    - flask-migrate==2.3.0
    - flask-restful==0.3.6
    - flask-sqlalchemy==2.3.2
    - gunicorn==19.9.0
    - itsdangerous==1.1.0
    - jinja2==2.10
    - mako==1.0.7
    - markupsafe==1.1.0
    - more-itertools==4.3.0
    - pathlib2==2.3.2
    - pluggy==0.8.0
    - psycopg2==2.7.6.1
    - py==1.7.0
    - pytest==4.0.0
    - python-dateutil==2.7.5
    - python-editor==1.0.3
    - pytz==2018.7
    - sqlalchemy==1.2.14
    - werkzeug==0.14.1
